-- 테스트 초기화 (개발기간에만 사용)
DROP TABLE IF EXISTS admin;
DROP TABLE IF EXISTS mall;
DROP TABLE IF EXISTS member;

-- 운영자(Admin)
create table admin
(
    admin_no            bigint generated by default as identity not null,
    id                  varchar(50)                             not null,
    name                varchar(50)                             not null,
    email               varchar(50)                             not null,
    phone_number        varchar(14),
    country            varchar(2),
    city               varchar(50),
    street             varchar(100),
    zipcode            varchar(10),
    detail_address     varchar(100),
    created_date       timestamp,
    last_modified_date timestamp,
    primary key (admin_no)
);
ALTER TABLE admin
    ADD CONSTRAINT UQ_ADM_ID UNIQUE (id);
ALTER TABLE admin
    ADD CONSTRAINT UQ_ADM_EMAIL UNIQUE (email);


-- 쇼핑몰(Mall)
create table mall
(
    mall_no            bigint generated by default as identity not null,
    admin_no           bigint                                  not null,
    name               varchar(50)                             not null,
    country_type       varchar(2) default 'KR'                 not null,
    country            varchar(2),
    city               varchar(50),
    street             varchar(100),
    zipcode            varchar(10),
    detail_address     varchar(100),
    status             varchar(10) default 'NORMAL',
    created_date       timestamp,
    last_modified_date timestamp,
    primary key (mall_no)
);
ALTER TABLE mall
    ADD CONSTRAINT UK_MALL_NAME UNIQUE (name);
ALTER TABLE mall
    ADD CONSTRAINT FK_MALL_ADMIN FOREIGN KEY (admin_no) REFERENCES admin;

-- 회원(Member)
create table member
(
    member_no             bigint generated by default as identity not null,
    mall_no            bigint                                  not null,
    id                 varchar(50)                             not null,
    name               varchar(10)                             not null,
    email              varchar(50)                             not null,
    gender             varchar(2)  default 'F',
    phone_number       varchar(14),
    birthdate          date,
    status             varchar(10) default 'ACTIVE',
    created_date       timestamp,
    last_modified_date timestamp,
    primary key (member_no)
);
ALTER TABLE member
    ADD CONSTRAINT UQ_MBR_ID UNIQUE (id);
ALTER TABLE member
    ADD CONSTRAINT UQ_MBR_EMAIL UNIQUE (email);
ALTER TABLE member
    ADD CONSTRAINT FK_MBR_MALL FOREIGN KEY (mall_no) REFERENCES mall;
