# 테스트를 완전히 격리된 환경에서 할 수 있도록 제공해준다.
# 테스트를 실행하면 test.resources내의 yml을 우선적으로 사용하도록 설정되어 있다.
# h2를 인메모리 모드로 구동하여 사용
# 즉, 인메모리 모드로 구성된 h2에 테이블을 생성하고 테스트를 진행한다. -> 로컬환경에서 테스트 용도로 사용하면 좋을 듯
spring:
  datasource:
    url: jdbc:h2:tcp://localhost/~/test
    username: sa
    password:
    driver-class-name: org.h2.Driver

  jpa:
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        format_sql: true
    show-sql: false
    defer-datasource-initialization: true

  sql:
    init:
      data-locations: classpath*:db/data.sql
      schema-locations: classpath*:db/schma.sql
      mode: always

  devtools:
    restart:
      enabled: false

#  sql:
#    init:
#      data-locations:
#      schema-locations:
#      mode: always

logging.level:
  org.hibernate.SQL: debug